
services:
  php_app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src/food_shop_project:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_shop
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d

volumes:
  db_data:
